version: "3.8"

services:
  guessrdb:
    container_name: guessrdb
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  guessrbackend:
    container_name: guessrbackend
    build: .
    restart: always
    depends_on:
      - guessrdb
    env_file:
      - .env
    ports:
      - "8000:8000"
    command:
      [
        "gunicorn",
        "main:app",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "--bind",
        "0.0.0.0:8000",
        "--workers",
        "4",
      ]

volumes:
  postgres_data:
